config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  root to: "users#index"
  resources :users do
    collection do
      get :user_to_all_rooms
      get :reserved_rooms
    end
  end
  resources :rooms do
  end
  resources :reservations do
    member do
      post :confirm
    end
  end


  get 'reservations/index'
  get 'rooms/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user, foreign_key: "user_id"
  has_many :reservations

  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, foreign_key: "user_id"
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
  end

  def new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if params[:back] || !@reservation.save

    else
      flash[:notice] = "予約に成功しました"
      redirect_to users_path
    end


  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice] = "予約を削除しました"
    redirect_to users_path
  end

  def confirm
    # binding.pry
    @current_user = User.find(params[:current_user_id])
    @reservation = Reservation.new(confirm_params)
    @room = Room.find(params[:id])
  end

  private

  def confirm_params
  params.permit(:user_id, :room_id, :room_name, :charge, :start_date, :end_date, :people, :avatar, :current_user_id, :id)#時間の計算をするために必要
  end
  def reservation_params
  params.require(:reservation).permit(:user_id, :room_id, :room_name, :charge, :start_date, :end_date, :people, :avatar)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    @room = Room.new
    @user = User.find(params[:id])
  end

  def create
    # @user = User.find(params[:user_id])
    # binding.pry
    @room = Room.new(room_params)
    # @user = User.find(params[:id])
    if @room.save
      flash[:notice] = "ルームを登録しました"
      redirect_to users_path
    else
      flash[:notice] = "ルームを登録できませんでした"
      render new_room_path
    end
  end

  def show
    @reservation = Reservation.new
    @room = Room.find(params[:id])
    @user = User.find(@room.user_id)#ルーム登録時に紐づけた登録者のuser_idからユーザー名を検索
    @current_user = User.find(params[:format])#ログイン中ユーザー取得
  end

  def edit
  end

  def update
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "ルームを削除しました"
    redirect_to users_path
  end

  private
  def room_params
    params.require(:room).permit(:room_name, :charge, :user_id, :address, :room_introduction, :avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @rooms = Room.all
    @reservations = Reservation.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "ユーザーを登録しました"
      redirect_to users_path
    else
      render new_user_path
    end
  end

  def show
    @room = Room.new
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "ユーザーを削除しました"
    redirect_to users_path
  end

  def user_to_all_rooms
    # binding.pry
    @rooms = Room.all
    @current_user = User.find(params[:format])
  end

  def reserved_rooms
    @current_user = User.find(params[:format])
    @reservations = Reservation.where(user_id: @current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:user_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hope</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/confirm.html.erb
<h1>予約確認画面</h1>
<h3>この部屋を予約しようとしているユーザー</h3>
<table>
  <tr>
    <th>ルーム画像:</th>
    <td>
      <% if @reservation.avatar? %>
        <%= image_tag @reservation.avatar, class: "room_image" %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th>予約者ID:</th>
    <td>
      <%= @current_user.id %>
    </td>
  </tr>
  <tr>
    <th>予約者名:</th>
    <td>
      <%= @current_user.user_name %>
    </td>
  </tr>
  <tr>
    <th>ルームネーム:</th>
    <td>
      <%= @room.room_name %>
    </td>
  </tr>
  <tr>
    <th>料金:</th>
    <td>
      <%= @room.charge %>円
    </td>
  </tr>
  <tr>
    <th>開始日:</th>
    <td>
      <%= params[:start_date] %>
    </td>
  </tr>
  <tr>
    <th>終了日:</th>
    <td>
      <%= params[:end_date] %>
    </td>
  </tr>
  <tr>
    <th>人数:</th>
    <td>
      <%= params[:people] %>人
    </td>
  </tr>
  <tr>
    <th>合計料金:</th>
    <td>
      <% sub_price = @reservation.charge * @reservation.people %>
      <% total_day = ((@reservation.end_date - @reservation.start_date)/3600/24+1).floor %>
        <% total_price = sub_price * total_day %>
        <%= total_price %>円
    </td>
  </tr>
</table>

  <%= form_with model: @reservation, local: true do |f| %>
    <%= f.hidden_field :user_id, :value=> @current_user.id %>
    <%= f.hidden_field :room_id, :value=> @room.id %>
    <%= f.hidden_field :room_name, :value=> @room.room_name %>
    <%= f.hidden_field :charge, :value=> @room.charge %>
    <%= f.hidden_field :start_date, :value=> params[:start_date] %>
    <%= f.hidden_field :end_date, :value=> params[:end_date] %>
    <%= f.hidden_field :people, :value=> params[:people] %>
    <%= f.hidden_field :avatar, :value=> @room.avatar %>

    <%= f.submit "確定する" %>
    <% end %>
    <%= link_to :back do %>
      <button>ルーム詳細に戻る</button>
    <% end %><!-- renderで作ろうとすると激ムズだったため -->

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<p>Find me in app/views/rooms/index.html.erb</p>

app/views/rooms/show.html.erb
<h3>ルーム予約</h3>
<h3>この部屋を予約しようとしているユーザー</h3>
<table>
  <tr>
    <th>ID</th>
    <td>
      <%= @current_user.id %>
    </td>
  </tr>
  <tr>
    <th>名前</th>
    <td>
      <%= @current_user.user_name %>
    </td>
  </tr>
</table>
-----------------------------------------------------------------
<%= form_with url: confirm_reservation_path do |f| %>
  <table>
    <tr>
      <th>
        <%= f.label :user_id ,"投稿者ID" %>
      </th>
      <td>
        <%= @room.user_id %>
      </td>
    </tr>
    <tr>
      <th>
        <%= f.label :user_name ,"投稿者名" %>
      </th>
      <td>
        <%= @user.user_name %>
      </td>
    </tr>
    <tr>
      <th>
        <%= f.label :user_id ,"ルームID" %>
      </th>
      <td>
        <%= @room.id %>
      </td>
    </tr>
    <tr>
      <th>
        <%= f.label :user_name ,"ルーム画像" %>
      </th>
      <td>
        <% if @room.avatar? %>
          <%= image_tag @room.avatar.url,class: "room_image" %>
            <% end %>
      </td>
    </tr>

    <tr>
      <th>
        <%= f.label :room_name ,"ルームネーム" %>
      </th>
      <td>
        <%=  @room.room_name %>
          <!-- ビューに表示されるが編集不可 -->
      </td>
    </tr>
    <tr>
      <th>
        <%= f.label :charge ,"料金" %>
      </th>
      <td>
        <%= @room.charge %>
          <!-- ビューに表示されるが編集不可 -->
      </td>
    </tr>
    <tr>
      <th>
        <%= f.label :start_date ,"開始日" %>
      </th>
      <td>
        <%= f.date_field :start_date %>
      </td>
    </tr>
    <tr>
      <th>
        <%= f.label :end_date ,"終了日" %>
      </th>
      <td>
        <%= f.date_field :end_date %>
      </td>
    </tr>
    <tr>
      <th>
        <%= f.label :people ,"人数" %>
      </th>
      <td>
        <%= f.number_field :people %>
      </td>
    </tr>
  </table>
      <%= f.submit "確認画面へ" %>
      <%= f.hidden_field :current_user_id, value: @current_user.id %>
      <%= f.hidden_field :charge, value: @room.charge %>
      <%= f.hidden_field :room_name, value: @room.room_name %>
      <%= f.hidden_field :avatar, value: @room.avatar
  %>
<% end %>

          <ul>
            <li>
              <%= link_to "ユーザー情報一覧に戻る" , :users %>
            </li>
          </ul>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<p>-----------------------------------------------------------------</p>
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>
<p>
  <%= link_to "ユーザー登録" , new_user_path %>
</p>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>名前</th>
      <th>ルーム登録</th>
      <th>ルーム予約</th>
      <th>ユーザー詳細(show)</th>
      <th>予約済みルーム</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
      <tr>
        <td>
          <%= u.id %>
        </td>
        <td>
          <%= u.user_name %>
        </td>
        <td>
          <%= link_to "ルーム登録", user_path(u)%>
        </td>
        <td>
          <%= link_to "ルーム予約",  user_to_all_rooms_users_path(u.id) %>
        </td>
        <td>
          <%= link_to "ユーザー詳細" , user_path(u) %>
        </td>
        <td>
          <%= link_to "予約済みルーム" , reserved_rooms_users_path(u) %>
        </td>
        <td>
          <%= link_to "削除" , u, method: :delete, data: { confirm: "本当に削除しますか？" } %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

<p>------------------------------------リレーション---------------------------------------------</p>
<h3>ルーム一覧</h3>
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>ルーム画像</th>
      <th>ルームネーム</th>
      <th>場所</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>登録者ID</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |r| %>
      <tr>
        <td>
          <%= r.id %>
        </td>
        <td>
        <% if r.avatar? %>
          <%= image_tag r.avatar.url,class: "room_image" %>
            <% end %>
        </td>
        <td>
          <%= r.room_name %>
        </td>
        <td>
          <%= r.address %>
        </td>
        <td>
          <%= r.room_introduction %>
        </td>
        <td>
          <%= r.charge %>円/日
        </td>
        <td>
          <%= r.user_id %>
        </td>
        <td>
          <%= link_to "削除" , r, method: :delete, data: { confirm: "本当に削除しますか？" } %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>
<p>---------------------------------------------------------------------------------</p>
<h3>予約済みルーム</h3>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>ルーム画像</th>
      <th>ルームネーム</th>
      <th>ルームID</th>
      <th>料金/日</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>人数</th>
      <th>合計料金</th>
      <th>予約者ID</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |r| %>
      <tr>
        <td>
          <%= link_to r.id, user_to_all_rooms_users_path(r.user_id) %>
        </td>
        <td>
          <% if r.avatar? %>
            <%= image_tag r.avatar, class: "room_image" %>
          <% end %>
        </td>
        <td>
          <%= r.room_id %>
        </td>
        <td>
          <%= r.room_name %>
        </td>
        <td>
          <%= r.charge %>
        </td>
        <td>
          <%= r.start_date.to_s(:datetime_jp) %>
        </td>
        <td>
          <%= r.end_date.to_s(:datetime_jp) %>
        </td>
        <td>
          <%= r.people %>
        </td>
        <td>
          <% sub_price = r.charge * r.people %>
            <% total_day=((r.end_date - r.start_date)/3600/24+1).floor %>
              <% total_price=sub_price * total_day %>
                <%= total_price %>円
        </td>
        <td>
          <%= r.user_id %>
        </td>
        <td>
          <%= link_to "削除" , r, method: :delete, data: { confirm: "本当に削除しますか？" } %>
        </td>
      </tr>
      <% end %>
  </tbody>

app/views/users/new.html.erb
<h1>ユーザー新規登録画面</h1>
<%= form_with model: @user, local: true do |u| %>
  <table>
    <tr>
      <th>
        <%= u.label :user_name ,"ユーザー名" %>
      </th>
      <td>
        <%= u.text_field :user_name %>
      </td>
    </tr>
  </table>
  <%= u.submit "登録完了する" %>
    <% end %>

app/views/users/reserved_rooms.html.erb
<h3>予約済みルーム</h3>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>ルームネーム</th>
      <th>料金/日</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>人数</th>
      <th>合計料金</th>
      <th>予約者ID</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |r| %>
      <tr>
        <td>
          <%= r.id %>
        </td>
        <td>
          <%= r.room_name %>
        </td>
        <td>
          <%= r.charge %>
        </td>
        <td>
          <%= r.start_date.to_s(:datetime_jp) %>
        </td>
        <td>
          <%= r.end_date.to_s(:datetime_jp) %>
        </td>
        <td>
          <%= r.people %>
        </td>
        <td>
          <% sub_price=r.charge * r.people %>
            <% total_day=((r.end_date - r.start_date)/3600/24+1).floor %>
              <% total_price=sub_price * total_day %>
                <%= total_price %>円
        </td>
        <td>
          <%= r.user_id %>
        </td>
        <td>
          <%= link_to "削除" , r, method: :delete, data: { confirm: "本当に削除しますか？" } %>
        </td>
      </tr>
      <% end %>
  </tbody>

app/views/users/show.html.erb
<h1>Rooms#new 新規ルーム登録画面</h1>
<%= flash[:notice] %>
  <%= form_with model: @room, local: true do |r| %>
    <table>
      <tr>
        <th>
          <%= r.label :room_name ,"ルームネーム" %>
        </th>
        <td>
          <%= r.text_field :room_name %>
        </td>
      </tr>
      <tr>
        <th>
          <%= r.label :address ,"場所" %>
        </th>
        <td>
          <%= r.text_field :address %>
        </td>
      </tr>
      <tr>
        <th>
          <%= r.label :room_introduction ,"ルーム紹介" %>
        </th>
        <td>
          <%= r.text_field :room_introduction %>
        </td>
      </tr>
      <tr>
        <th>
          <%= r.label :charge ,"料金/日" %>
        </th>
        <td>
          <%= r.text_field :charge %>
        </td>
      </tr>
        <th>
          <%= r.label :avatar, "ルーム画像" %>
        </th>
        <td>
          <%= r.file_field :avatar %>
        </td>
    </table>
      <%= r.hidden_field :user_id, value: @user.id %>
        <%= r.submit "登録完了する" %>
          <% end %>
        <% if @room.avatar? %>
            <strong>Avatar:</strong>
            <%= image_tag @room.avatar.url %>
          <% end %>

app/views/users/user_to_all_rooms.html.erb
<h3>この部屋を予約しようとしているユーザー</h3>
<table>
  <tr>
    <th>ID</th>
    <td>
      <%= params[:format] %>
    </td>
  </tr>
  <tr>
    <th>名前</th>
    <td>
      <%= @current_user.user_name %>
    </td>
  </tr>
  <table>
  <h3>ルーム一覧</h3>
  <thead>
    <tr>
      <th>id</th>
      <th>ルームネーム</th>
      <th>料金</th>
      <th>投稿者ID</th>
      <th>予約(show)</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |r| %>
      <tr>
        <td>
          <%= r.id %>
        </td>
        <td>
          <%= r.room_name %>
        </td>
        <td>
          <%= r.charge %>
        </td>
        <td>
          <%= r.user_id %>
        </td>
        <td>
          <%= link_to "予約する" , room_path(r,@current_user) %>
        </td>
        <td>
          <%= link_to "削除" , r, method: :delete, data: { confirm: "本当に削除しますか？" } %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>